Issue #SB-28693 feat: DIAL Code context Update and Read
project-sunbird/sunbird-dial-service pull request #38
Opened 2022-03-10 10:58 UTC by Jayaprakash8887

2022-03-15 10:49 UTC, maheshkumargangula requested changes

2022-03-15 11:35 UTC, Jayaprakash8887 commented on pom.xml
> +        </dependency>
No, not specific to json-ld. Just using a standard library.

2022-03-15 12:06 UTC, Jayaprakash8887 commented on pom.xml
> +        <dependency>
I am not sure on how to verify this

2022-03-17 06:21 UTC, maheshkumargangula submitted a review, later dismissed

2022-03-17 12:05 UTC, maheshkumargangula approved these changes

2022-03-17 12:05 UTC, merged